version: '3.1'

services:
  mem-app:
    image: docker.io/bitnami/laravel:10
    container_name: mem-app
    ports:
      - '8085:8000'
    environment:
      - SALT=${SALT}
      - SALT2=${SALT2}
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USERNAME=root
      - DB_DATABASE=memini
    volumes:
      - './app:/app'
    depends_on:
      - db

  composer:
    image: composer:2.7.1
    container_name: composer-mem
    working_dir: /app
    command: composer install
    volumes:
      - './app:/app'
    depends_on:
      - mem-app

  db:
    image: mysql:latest
    container_name: dd-mem
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes: 
      - ./db/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: example

  myadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    links: 
      - db
    ports:
      - 8082:80

  cmu-redis:
    image: redis
    container_name: redis-mem
    restart: always
    volumes: 
      - ./db/redis/data:/data
      - ./db/redis/etc/redis.conf:/usr/local/etc/redis/redis.conf